"""add payment_orders table

Revision ID: 7e292ffc7777
Revises: eec7a9fbd1cd
Create Date: 2026-02-21 23:52:41.474480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e292ffc7777'
down_revision: Union[str, Sequence[str], None] = 'eec7a9fbd1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_key', sa.String(length=200), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('point_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('fail_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['point_transaction_id'], ['point_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_key')
    )
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_orders_order_id'), ['order_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_orders_order_id'))
        batch_op.drop_index(batch_op.f('ix_payment_orders_id'))

    op.drop_table('payment_orders')
    # ### end Alembic commands ###
