"""add social auth fields to user

Revision ID: eec7a9fbd1cd
Revises: 8c517d3e3d3a
Create Date: 2026-02-20 16:21:12.048103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec7a9fbd1cd'
down_revision: Union[str, Sequence[str], None] = '8c517d3e3d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.alter_column('a_value',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('net_cost',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('social_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_social_id'), ['social_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_social_id'))
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('social_id')
        batch_op.drop_column('social_provider')

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.alter_column('net_cost',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('a_value',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
